name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v41.0.18
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
